### ISSUE TITLE
Missing (build) files

### ISSUE THREAD

**Issue by crackytsi** [baumerits/putty-pkix#1]
Hi @svenso @rba 
I'm a little confused, based on your github project page you link to a build file, but this is missing.
It seems that there are some other files missing as well.
Can you please add these files?

thanks

**Comment by rba** [comment]
@crackytsi You're correct. This is because in the past it was just a patch for putty. To keep maintenance simpler we decided fork first the original putty and then add the changes on top of it. If you clone the repo you can build it like upstream putty.

Additionally there is a binary release here: https://github.com/baumerits/putty-pkix/releases/tag/0.73

**Comment by crackytsi** [comment]
Ok thanks @rba
